"""empty message

Revision ID: 8dd82ef75c8b
Revises: 
Create Date: 2019-11-26 18:33:07.330421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd82ef75c8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='demo'
    )
    op.create_index(op.f('ix_demo_user_id'), 'user', ['id'], unique=False, schema='demo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_user_id'), table_name='user', schema='demo')
    op.drop_table('user', schema='demo')
    # ### end Alembic commands ###
